"""auto-generate task_log table

Revision ID: 00e9268f3a57
Revises: 0749f70f229f
Create Date: 2021-12-23 17:21:17.252269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e9268f3a57'
down_revision = '0749f70f229f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task_log',
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('initiative_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column(
            'logged_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column('logged_by', sa.Integer(), nullable=False),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['initiative_id'],
            ['initiative.initiative_id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['logged_by'],
            ['employee.employee_id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(
        op.f('ix_task_log_task_id'),
        'task_log',
        ['task_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_log_task_id'), table_name='task_log')
    op.drop_table('task_log')
    # ### end Alembic commands ###
