"""auto-generate rating table

Revision ID: 3f5df9b9c5dc
Revises: 6d6dc1040790
Create Date: 2021-12-23 17:51:57.846624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5df9b9c5dc'
down_revision = '6d6dc1040790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rating',
        sa.Column('rating_id', sa.Integer(), nullable=False),
        sa.Column('initiative_id', sa.Integer(), nullable=False),
        sa.Column('point', sa.Integer(), nullable=False),
        sa.Column('given_by', sa.Integer(), nullable=False),
        sa.Column(
            'given_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['given_by'],
            ['employee.employee_id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['initiative_id'],
            ['initiative.initiative_id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index(
        op.f('ix_rating_rating_id'),
        'rating',
        ['rating_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_rating_id'), table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###
