"""auto-generate review table

Revision ID: 6d6dc1040790
Revises: f7f5982a57dc
Create Date: 2021-12-23 17:47:25.915990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6dc1040790'
down_revision = 'f7f5982a57dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'review',
        sa.Column('review_id', sa.Integer(), nullable=False),
        sa.Column('initiative_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('given_by', sa.Integer(), nullable=False),
        sa.Column(
            'given_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['given_by'],
            ['employee.employee_id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['initiative_id'],
            ['initiative.initiative_id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(
        op.f('ix_review_review_id'),
        'review',
        ['review_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_review_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
