"""auto-generate status_code table

Revision ID: d3f4366dda5b
Revises: ddcb5575314f
Create Date: 2021-12-23 16:24:00.461308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f4366dda5b'
down_revision = 'ddcb5575314f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'status_code',
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column('updated_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['employee.employee_id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['updated_by'],
            ['employee.employee_id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(
        op.f('ix_status_code_status_id'),
        'status_code',
        ['status_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_code_status_id'), table_name='status_code')
    op.drop_table('status_code')
    # ### end Alembic commands ###
