"""auto-gen-employee table

Revision ID: ddcb5575314f
Revises: 18f3245cd66f
Create Date: 2021-12-23 16:09:46.754676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcb5575314f'
down_revision = '18f3245cd66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employee',
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('employee_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column(
            'employee_type_id',
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['employee_type_id'],
            ['employee_type.employee_type_id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('employee_id'),
        sa.UniqueConstraint('email')
    )

    op.create_index(
        op.f('ix_employee_employee_id'),
        'employee',
        ['employee_id'],
        unique=False
    )

    op.drop_constraint(
        'employee_type_role_name_key',
        'employee_type',
        type_='unique'
    )
    op.create_index(
        op.f('ix_employee_type_employee_type_id'),
        'employee_type',
        ['employee_type_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_employee_type_role_name'),
        'employee_type',
        ['role_name'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_employee_type_role_name'),
        table_name='employee_type'
    )
    op.drop_index(
        op.f('ix_employee_type_employee_type_id'),
        table_name='employee_type'
    )
    op.create_unique_constraint(
        'employee_type_role_name_key',
        'employee_type',
        ['role_name']
    )
    op.drop_index(
        op.f('ix_employee_employee_id'),
        table_name='employee'
    )
    op.drop_table('employee')
    # ### end Alembic commands ###
