"""auto-generate subscription table

Revision ID: f7f5982a57dc
Revises: 00e9268f3a57
Create Date: 2021-12-23 17:33:59.721176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f5982a57dc'
down_revision = '00e9268f3a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subscription',
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('subscribed_by', sa.Integer(), nullable=False),
        sa.Column('initiative_id', sa.Integer(), nullable=False),
        sa.Column(
            'subscribed_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['initiative_id'],
            ['initiative.initiative_id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['subscribed_by'],
            ['employee.employee_id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(
        op.f('ix_subscription_subscription_id'),
        'subscription',
        ['subscription_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_subscription_subscription_id'),
        table_name='subscription'
    )
    op.drop_table('subscription')
    # ### end Alembic commands ###
