"""auto-generate updated_at in rating table

Revision ID: f82236e87b4b
Revises: a95f88b1ac29
Create Date: 2021-12-25 15:24:26.435172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82236e87b4b'
down_revision = 'a95f88b1ac29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rating',
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'updated_at')
    # ### end Alembic commands ###
